<h1>Bandas</h1>
<br />

<p>
    <a href="<?php echo $this->url('album-actions', array('controller' => 'band','action' => 'new')); ?>">Nova</a>
</p>

<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Gravadora</th>
        <th>Ação</th>
    </tr>

    <?php foreach($this->data as $mateus): ?>
        <tr>
            <td><?php echo $mateus->getId(); ?></td>
            <td><?php echo $mateus->getName(); ?></td>
            <td><?php echo $mateus->getRecords(); ?></td>
            <td>
                <a href="<?php echo $this->url('album-forms',
                    array('controller'=>'band','action'=>'edit','id' => $mateus->getId())); ?>">Editar</a>
                <a href="<?php echo $this->url('album-forms',
                    array('controller'=>'band','action'=>'delete','id' => $mateus->getId())); ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>
<br />

<?php echo $this->paginationControl($this->data,'Sliding','paginator'); ?>