<h3>Editando Album</h3>

<br />

<?php
    $form = $this->form;

    $form->setAttribute('action', $this->url('album-forms', array('controller'=>'album','action' => 'edit')));

    $form->prepare();
    echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('year'));

        echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>