<h3>Novo Albúm</h3>

<br />

<?php
    $form = $this->form;

    $form->setAttribute('action', '/music/album/new');

    $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('year'));
        echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>