<h3>Editar Autor</h3>

<br />

<?php
    $form = $this->form;

    $form->setAttribute('action', $this->url('book-forms', array('controller'=>'authors','action' => 'edit')));

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('name'));

    echo $this->formRow($form->get('email'));
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>