<h3>Novo Autor</h3>

<br />

<?php
    $form = $this->form;

    $form->setAttribute('action', '/book/authors/new');

    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('id'));
    echo $this->formRow($form->get('name'))."<br>";

    echo $this->formRow($form->get('email'))."<br>";
    echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>