<h3>Editando Musica</h3>

<br />

<?php
    $form = $this->form;

    $form->setAttribute('action', $this->url('album-forms', array('controller'=>'music','action' => 'edit')));

    $form->prepare();
        echo $this->form()->openTag($form);
        echo $this->formHidden($form->get('id'));
        echo $this->formRow($form->get('name'));
        echo $this->formRow($form->get('duration'));
        echo $this->formRow($form->get('album'))."<br/>";
        echo $this->formSubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>